services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    env_file:
      - apps/backend/.env.production
    image: ${DOCKER_IMAGE_TAG}
    ports:
      - "8888:8888"
    environment:
      - BUN_ENV=production
      - PORT=8888
    restart: always
