services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    image: ${DOCKER_IMAGE}
    ports:
      - "8888:8888"
    environment:
      - NODE_ENV=production
      - PORT=8888
    restart: always
