services:
  github-mcp-server:
    container_name: github-mcp-server
    image: ghcr.io/github/github-mcp-server
    environment:
      GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN}
    stdin_open: true
    tty: true
    restart: "no"
